version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - ./app:/var/www/html
    depends_on:
      - db

  db:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: userdb
      MYSQL_USER: lampuser
      MYSQL_PASSWORD: password123
      MYSQL_ROOT_PASSWORD: rootpass
    volumes:
      - db_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  tests:
    build:
      context: .
      dockerfile: Dockerfile.test
    depends_on:
      - web

volumes:
  db_data: